//Login Layout

"use client"
import '../globals.css'
import { Inter } from 'next/font/google'
// import CustomNavbar from '../components/CustomNavbar'
import Footer from '../../components/Footer'
import TT_Logo from '../assets/logo.png'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <CustomNavbar /> */}
      <div className="bg-red-600 font-semibold text-center text-4xl mt-1 justify-normal"> 
        <h1>Welcome To Trendy Taste</h1>
      </div>
       <div className="mb-5 flex justify">
        {/* <div className=" justify-center"> */}
        <Image src={TT_Logo} width={650} height={550} alt="" />
          {/* </div> */}
        <div className="h-9">
         {children} 
         </div>
         </div>
        <Footer />
        </body>
    </html>
  )
}


